#!/bin/sh

### BEGIN INIT INFO
# Provides:          onos
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: onos
### END INIT INFO

prog=onos
export JAVA_HOME=/usr/lib/jvm/java-8-oracle

cd /opt/onos/bin/
start(){
        echo $"Starting $prog..."
        ./onos-service &
        }
stop(){
        PID=`ps aux | grep java | grep karaf | awk '{print $2}'`
        echo $"Stopping $prog $PID"
        kill -9 $PID
        sleep 2
        }
status(){
        PID=`ps aux | grep java | grep karaf | awk '{print $2}'`
        if test -z $PID
        then
          echo "onos stop/waiting"
          exit 1
        else
          echo "onos start/running, process $PID."
          exit 0
        fi
        }

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
        status
        ;;
  *)
        echo "Please use: $0 {start|stop|status}"
        exit 1
        ;;
esac
